region: ${env:AWS_REGION}
timeout: 30
runtime: nodejs20.x
memorySize: 1280
versionFunctions: false
stage: ${env:STAGE}
tracing:
  lambda: true
deploymentBucket: ${env:S3_BUCKET}
vpc:
  securityGroupIds:
    - ${env:AWS_SECURITY_GROUP_ID}
  subnetIds:
    - ${env:AWS_SUBNET_ID_1}
    - ${env:AWS_SUBNET_ID_2}
    - ${env:AWS_SUBNET_ID_3}
    - ${env:AWS_SUBNET_ID_4}
environment:
  http_host: ${env:HTTP_HOST}
  http_port: ${env:HTTP_PORT}
  google_client_id: ${env:GOOGLE_CLIENT_ID}
  google_client_secret: ${env:GOOGLE_CLIENT_SECRET}
  google_callback_base_url: ${env:GOOGLE_CALLBACK_BASE_URL}
  google_callback_path: auth/google/callback
  refresh_token_expiration: 2419200
  client_url: ${env:CLIENT_URL}
  db_host: ${env:DB_HOST}
  db_port: 5432
  db_database: postgres
  db_username: postgres
  db_password: ${env:DB_PASSWORD}
