service: serverless-example

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

functions:
  main:
    handler: dist/main2.handler
    events:
      - http:
          method: any
          path: /{any+}
