region: ${env:AWS_REGION}
timeout: 30
runtime: nodejs20.x
memorySize: 1280
versionFunctions: false
stage: ${env:STAGE}
tracing:
  lambda: true
deploymentBucket: ${env:S3_BUCKET}
vpc:
  securityGroupIds:
    - ${env:AWS_SECURITY_GROUP_ID}
  subnetIds:
    - ${env:AWS_SUBNET_ID_1}
    - ${env:AWS_SUBNET_ID_2}
    - ${env:AWS_SUBNET_ID_3}
    - ${env:AWS_SUBNET_ID_4}
#add env variables here
