region: ${env:AWS_REGION}
timeout: 30
runtime: nodejs20.x
memorySize: 1280
versionFunctions: false
stage: ${env:STAGE}
tracing:
  lambda: true
deploymentBucket: ${env:S3_BUCKET}
vpc:
  securityGroupIds:
    - ${env:AWS_SECURITY_GROUP_ID}
  subnetIds:
    - ${env:AWS_SUBNET_ID_1}
    - ${env:AWS_SUBNET_ID_2}
    - ${env:AWS_SUBNET_ID_3}
    - ${env:AWS_SUBNET_ID_4}
environment:
  DatabaseUrl: ${ssm:/aws/reference/secretsmanager/ASSET_MANAGER_DATABASE_URL}
  AssetsBucketName: ${env:ASSETS_BUCKET_NAME}
  AssetsBukcetBaseUrl: ${env:ASSETS_BUKCET_BASE_URL}
  BitlyAccessToken: ${env:BITLY_ACCESS_TOKEN}
  StageName: ${env:STAGE}
  STAGE_NAME: ${env:STAGE}
